---
- name: Creates directory for web files
  file: path=/var/www/html state=directory

- name: Download WordPress
  get_url: url={{ wordpress_url }} dest=/var/www/html/wordpress.tar.gz force=yes

- name: Extract archive
  unarchive: src=/var/www/html/wordpress.tar.gz dest=/var/www/html/ copy=no creates={{ wordpress_dir }}

- name: change the Ownership to www-data
  file: path={{ wordpress_dir }} state=directory mode=755 owner=www-data group=www-data
 
- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
