---
- name: Creates directory for web files
  file: path=/var/www/html state=directory

- name: Download WordPress
  get_url: url={{ wordpress_url }} dest=/var/www/html/wordpress.tar.gz force=yes

- name: Extract archive
  unarchive: src=/var/www/html/wordpress.tar.gz dest=/var/www/html/ copy=no #creates={{ wordpress_dir }}
 
- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
  
- name: Check the Status of Unzip Directory
  stat: path=/var/www/html/wordpress
  register: wordpress_stat

#- name: Move foo to bar
#  command: mv /var/www/html/wordpress {{ wordpress_dir }}
#  when: wordpress_stat.stat.exists

- name: change the Ownership to www-data
  file: path=/var/www/html/wordpress state=directory mode=755 owner=www-data group=www-data recurse=yes
